import type { MetadataRoute } from "next";

/**
 * Web app manifest.
 *
 * Generated by Next rather than hand-written JSON so the identity values here
 * stay in one file with the rest of the app metadata.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Pitik — Made for moments together",
    short_name: "Pitik",
    description:
      "A nostalgic digital camera and photobooth for the people you're with. Works offline; your photos stay on your device.",
    id: "/",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#0b0908",
    theme_color: "#0b0908",
    categories: ["photo", "lifestyle", "social"],
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: "/icons/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
    // Long-press the installed icon to go straight to the two things people
    // actually open the app to do.
    shortcuts: [
      {
        name: "Open the camera",
        short_name: "Camera",
        url: "/camera",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }],
      },
      {
        name: "Start a photobooth",
        short_name: "Photobooth",
        url: "/booth",
        icons: [{ src: "/icons/icon-192.png", sizes: "192x192" }],
      },
    ],
  };
}
